/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/conversations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List conversations */
    get: {
      parameters: {
        query?: {
          platform?: string;
          codebaseId?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ConversationListResponse'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    /** Create a new conversation */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateConversationBody'];
        };
      };
      responses: {
        /** @description Created conversation */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CreateConversationResponse'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/conversations/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a conversation by platform conversation ID */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Conversation */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Conversation'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    /** Soft-delete a conversation */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Deleted */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['SuccessResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    /** Update a conversation (title) */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['UpdateConversationBody'];
        };
      };
      responses: {
        /** @description Updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['SuccessResponse'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    trace?: never;
  };
  '/api/conversations/{id}/messages': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List message history for a conversation */
    get: {
      parameters: {
        query?: {
          limit?: string;
        };
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Message list */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MessageListResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/conversations/{id}/message': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Send a message (JSON or multipart with file uploads)
     * @description Accepts `application/json` with `{ message: string }` or `multipart/form-data` with a `message` field and optional file attachments (max 5 files, 10 MB each).
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Accepted */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['DispatchResponse'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/codebases': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List registered codebases */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CodebaseListResponse'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    /** Register a codebase (clone from URL or register local path) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['AddCodebaseBody'];
        };
      };
      responses: {
        /** @description Codebase already existed */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Codebase'];
          };
        };
        /** @description Codebase created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Codebase'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/codebases/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a codebase by ID */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Codebase */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Codebase'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    /** Delete a codebase and clean up associated resources */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Deleted */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['DeleteCodebaseResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/codebases/{id}/env': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List env vars for a codebase */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Env vars for codebase */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CodebaseEnvVarsResponse'];
          };
        };
        /** @description Codebase not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    /** Set (upsert) an env var for a codebase */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['SetEnvVarBody'];
        };
      };
      responses: {
        /** @description Env var set */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['EnvVarMutationResponse'];
          };
        };
        /** @description Codebase not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/codebases/{id}/env/{key}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete an env var from a codebase */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
          key: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Env var deleted */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['EnvVarMutationResponse'];
          };
        };
        /** @description Codebase not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workflows': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List available workflows */
    get: {
      parameters: {
        query?: {
          cwd?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WorkflowListResponse'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workflows/{name}/run': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Run a workflow via the orchestrator (JSON or multipart with file uploads)
     * @description Accepts `application/json` with `{ conversationId, message }` or `multipart/form-data` with `conversationId`, `message`, and optional file attachments (max 5 files, 10 MB each).
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          name: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Accepted */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['DispatchResponse'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/dashboard/runs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List enriched workflow runs for the Command Center dashboard */
    get: {
      parameters: {
        query?: {
          status?: string;
          codebaseId?: string;
          search?: string;
          after?: string;
          before?: string;
          limit?: string;
          offset?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['DashboardRunsResponse'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workflows/runs/{runId}/cancel': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Cancel a workflow run */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          runId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Cancelled */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CancelWorkflowRunResponse'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workflows/runs/{runId}/resume': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Resume a failed workflow run (dispatches resume on the parent web conversation) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          runId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Resumed */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WorkflowRunActionResponse'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workflows/runs/{runId}/abandon': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Abandon a workflow run (mark as failed) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          runId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Abandoned */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WorkflowRunActionResponse'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workflows/runs/{runId}/approve': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Approve a paused workflow run */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          runId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['ApproveWorkflowRunBody'];
        };
      };
      responses: {
        /** @description Approved */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WorkflowRunActionResponse'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workflows/runs/{runId}/reject': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reject a paused workflow run */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          runId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['RejectWorkflowRunBody'];
        };
      };
      responses: {
        /** @description Rejected */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WorkflowRunActionResponse'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workflows/runs/{runId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get workflow run details with events */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          runId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Workflow run detail */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WorkflowRunDetail'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    /** Delete a workflow run and its events */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          runId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Deleted */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WorkflowRunActionResponse'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workflows/runs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List workflow runs */
    get: {
      parameters: {
        query?: {
          conversationId?: string;
          status?: string;
          codebaseId?: string;
          limit?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WorkflowRunListResponse'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workflows/runs/by-worker/{platformId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Look up a workflow run by its worker conversation platform ID */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          platformId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Workflow run */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WorkflowRunByWorkerResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workflows/validate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Validate a workflow definition without saving */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ValidateWorkflowBody'];
        };
      };
      responses: {
        /** @description Validation result */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ValidateWorkflowResponse'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workflows/{name}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Fetch a single workflow definition */
    get: {
      parameters: {
        query?: {
          cwd?: string;
        };
        header?: never;
        path: {
          name: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Workflow definition */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['GetWorkflowResponse'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    /** Save (create or update) a workflow */
    put: {
      parameters: {
        query?: {
          cwd?: string;
          source?: 'project' | 'global';
        };
        header?: never;
        path: {
          name: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['SaveWorkflowBody'];
        };
      };
      responses: {
        /** @description Saved workflow */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['GetWorkflowResponse'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    post?: never;
    /** Delete a user-defined workflow */
    delete: {
      parameters: {
        query?: {
          cwd?: string;
          source?: 'project' | 'global';
        };
        header?: never;
        path: {
          name: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Deleted */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['DeleteWorkflowResponse'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/commands': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List available command names for the workflow node palette */
    get: {
      parameters: {
        query?: {
          cwd?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CommandListResponse'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/runs/{runId}/artifacts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List a run's artifact files
     * @description Walks the run's artifact directory and returns relative file paths with size + mtime. Drives the console Artifacts tab. Returns `{ files: [] }` when the run has no codebase or the codebase name is not in `owner/repo` form.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          runId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ListArtifactsResponse'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/config': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get read-only configuration (safe subset) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Configuration */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ConfigResponse'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/config/assistants': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update assistant configuration */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['UpdateAssistantConfigBody'];
        };
      };
      responses: {
        /** @description Updated configuration */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ConfigResponse'];
          };
        };
        /** @description Invalid request body */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    trace?: never;
  };
  '/api/providers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List registered AI providers */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of registered providers */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProviderListResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/codebases/{id}/environments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List isolation environments for a codebase */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of isolation environments */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CodebaseEnvironmentsResponse'];
          };
        };
        /** @description Codebase not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health check */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Health status */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['HealthResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/update-check': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Check for available updates */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Update check result */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['UpdateCheckResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Conversation: {
      id: string;
      platform_type: string;
      platform_conversation_id: string;
      codebase_id: string | null;
      cwd: string | null;
      isolation_env_id: string | null;
      ai_assistant_type: string;
      title: string | null;
      hidden: boolean;
      deleted_at: string | null;
      last_activity_at: string | null;
      created_at: string;
      updated_at: string;
    };
    ConversationListResponse: components['schemas']['Conversation'][];
    Error: {
      error: string;
    };
    CreateConversationResponse: {
      conversationId: string;
      id: string;
      dispatched?: boolean;
    };
    CreateConversationBody: {
      codebaseId?: string;
      message?: string;
    };
    SuccessResponse: {
      success: boolean;
    };
    UpdateConversationBody: {
      title?: string;
    };
    Message: {
      id: string;
      conversation_id: string;
      /** @enum {string} */
      role: 'user' | 'assistant';
      content: string;
      metadata: string;
      created_at: string;
    };
    MessageListResponse: components['schemas']['Message'][];
    DispatchResponse: {
      accepted: boolean;
      status: string;
    };
    CodebaseCommand: {
      path: string;
      description: string;
    };
    Codebase: {
      id: string;
      name: string;
      repository_url: string | null;
      default_cwd: string;
      ai_assistant_type: string;
      commands: {
        [key: string]: components['schemas']['CodebaseCommand'];
      };
      created_at: string;
      updated_at: string;
    };
    CodebaseListResponse: components['schemas']['Codebase'][];
    AddCodebaseBody: {
      url?: string;
      path?: string;
    };
    DeleteCodebaseResponse: {
      success: boolean;
    };
    CodebaseEnvVarsResponse: {
      keys: string[];
    };
    EnvVarMutationResponse: {
      success: boolean;
    };
    SetEnvVarBody: {
      key: string;
      value: string;
    };
    DagNode: {
      id: string;
      depends_on?: string[];
      when?: string;
      /** @enum {string} */
      trigger_rule?: 'all_success' | 'one_success' | 'none_failed_min_one_success' | 'all_done';
      model?: string;
      provider?: string;
      /** @enum {string} */
      context?: 'fresh' | 'shared';
      output_format?: {
        [key: string]: unknown;
      };
      allowed_tools?: string[];
      denied_tools?: string[];
      idle_timeout?: number;
      retry?: {
        max_attempts: number;
        delay_ms?: number;
        /** @enum {string} */
        on_error?: 'transient' | 'all';
      };
      hooks?: {
        PreToolUse?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
        PostToolUse?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
        PostToolUseFailure?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
        Notification?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
        UserPromptSubmit?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
        SessionStart?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
        SessionEnd?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
        Stop?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
        SubagentStart?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
        SubagentStop?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
        PreCompact?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
        PermissionRequest?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
        Setup?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
        TeammateIdle?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
        TaskCompleted?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
        Elicitation?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
        ElicitationResult?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
        ConfigChange?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
        WorktreeCreate?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
        WorktreeRemove?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
        InstructionsLoaded?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
      };
      mcp?: string;
      skills?: string[];
      agents?: {
        [key: string]: {
          description: string;
          prompt: string;
          model?: string;
          tools?: string[];
          disallowedTools?: string[];
          skills?: string[];
          maxTurns?: number;
        };
      };
      /** @enum {string} */
      effort?: 'low' | 'medium' | 'high' | 'max';
      thinking?:
        | {
            /** @enum {string} */
            type: 'adaptive';
          }
        | {
            /** @enum {string} */
            type: 'enabled';
            budgetTokens?: number;
          }
        | {
            /** @enum {string} */
            type: 'disabled';
          };
      maxBudgetUsd?: number;
      systemPrompt?: string;
      fallbackModel?: string;
      betas?: string[];
      sandbox?: {
        enabled?: boolean;
        autoAllowBashIfSandboxed?: boolean;
        allowUnsandboxedCommands?: boolean;
        network?: {
          allowedDomains?: string[];
          allowManagedDomainsOnly?: boolean;
          allowUnixSockets?: string[];
          allowAllUnixSockets?: boolean;
          allowLocalBinding?: boolean;
          httpProxyPort?: number;
          socksProxyPort?: number;
        };
        filesystem?: {
          allowWrite?: string[];
          denyWrite?: string[];
          denyRead?: string[];
        };
        ignoreViolations?: {
          [key: string]: string[];
        };
        enableWeakerNestedSandbox?: boolean;
        enableWeakerNetworkIsolation?: boolean;
        excludedCommands?: string[];
        ripgrep?: {
          command: string;
          args?: string[];
        };
      };
      always_run?: boolean;
      command?: string;
      prompt?: string;
      bash?: string;
      loop?: {
        prompt: string;
        until: string;
        max_iterations: number;
        /** @default false */
        fresh_context: boolean;
        until_bash?: string;
        interactive?: boolean;
        gate_message?: string;
      };
      approval?: {
        message: string;
        capture_response?: boolean;
        on_reject?: {
          prompt: string;
          max_attempts?: number;
        };
      };
      cancel?: string;
      script?: string;
      /** @enum {string} */
      runtime?: 'bun' | 'uv';
      deps?: string[];
      timeout?: number;
    };
    WorkflowDefinition: {
      name: string;
      description: string;
      provider?: string;
      model?: string;
      /** @enum {string} */
      modelReasoningEffort?: 'minimal' | 'low' | 'medium' | 'high' | 'xhigh';
      /** @enum {string} */
      webSearchMode?: 'disabled' | 'cached' | 'live';
      additionalDirectories?: string[];
      interactive?: boolean;
      /** @enum {string} */
      effort?: 'low' | 'medium' | 'high' | 'max';
      thinking?:
        | {
            /** @enum {string} */
            type: 'adaptive';
          }
        | {
            /** @enum {string} */
            type: 'enabled';
            budgetTokens?: number;
          }
        | {
            /** @enum {string} */
            type: 'disabled';
          };
      fallbackModel?: string;
      betas?: string[];
      sandbox?: {
        enabled?: boolean;
        autoAllowBashIfSandboxed?: boolean;
        allowUnsandboxedCommands?: boolean;
        network?: {
          allowedDomains?: string[];
          allowManagedDomainsOnly?: boolean;
          allowUnixSockets?: string[];
          allowAllUnixSockets?: boolean;
          allowLocalBinding?: boolean;
          httpProxyPort?: number;
          socksProxyPort?: number;
        };
        filesystem?: {
          allowWrite?: string[];
          denyWrite?: string[];
          denyRead?: string[];
        };
        ignoreViolations?: {
          [key: string]: string[];
        };
        enableWeakerNestedSandbox?: boolean;
        enableWeakerNetworkIsolation?: boolean;
        excludedCommands?: string[];
        ripgrep?: {
          command: string;
          args?: string[];
        };
      };
      worktree?: {
        enabled?: boolean;
      };
      mutates_checkout?: boolean;
      tags?: string[];
      nodes: components['schemas']['DagNode'][];
    };
    /** @enum {string} */
    WorkflowSource: 'project' | 'bundled' | 'global';
    WorkflowListEntry: {
      workflow: components['schemas']['WorkflowDefinition'];
      source: components['schemas']['WorkflowSource'];
    };
    WorkflowLoadError: {
      filename: string;
      error: string;
      /** @enum {string} */
      errorType: 'read_error' | 'parse_error' | 'validation_error';
    };
    WorkflowListResponse: {
      workflows: components['schemas']['WorkflowListEntry'][];
      errors?: components['schemas']['WorkflowLoadError'][];
    };
    /** @enum {string} */
    WorkflowRunStatus: 'pending' | 'running' | 'completed' | 'failed' | 'cancelled' | 'paused';
    WorkflowRun: {
      id: string;
      workflow_name: string;
      conversation_id: string;
      parent_conversation_id: string | null;
      codebase_id: string | null;
      status: components['schemas']['WorkflowRunStatus'];
      user_message: string;
      metadata: {
        [key: string]: unknown;
      };
      started_at: string;
      completed_at: string | null;
      last_activity_at: string | null;
      working_path: string | null;
    };
    DashboardWorkflowRun: components['schemas']['WorkflowRun'] & {
      codebase_name: string | null;
      platform_type: string | null;
      worker_platform_id: string | null;
      parent_platform_id: string | null;
      current_step_name: string | null;
      total_steps: number | null;
      /** @enum {string|null} */
      current_step_status: 'running' | 'completed' | 'failed' | null;
      agents_completed: number | null;
      agents_failed: number | null;
      agents_total: number | null;
    };
    DashboardRunsResponse: {
      runs: components['schemas']['DashboardWorkflowRun'][];
      total: number;
      counts: {
        all: number;
        running: number;
        completed: number;
        failed: number;
        cancelled: number;
        pending: number;
        paused: number;
      };
    };
    CancelWorkflowRunResponse: {
      success: boolean;
      message: string;
    };
    WorkflowRunActionResponse: {
      success: boolean;
      message: string;
    };
    ApproveWorkflowRunBody: {
      comment?: string;
    };
    RejectWorkflowRunBody: {
      reason?: string;
    };
    WorkflowRunListResponse: {
      runs: components['schemas']['WorkflowRun'][];
    };
    WorkflowRunByWorkerResponse: {
      run: components['schemas']['WorkflowRun'];
    };
    WorkflowEvent: {
      id: string;
      workflow_run_id: string;
      event_type: string;
      step_index: number | null;
      step_name: string | null;
      data: {
        [key: string]: unknown;
      };
      created_at: string;
    };
    WorkflowRunDetail: {
      run: components['schemas']['WorkflowRun'] & {
        worker_platform_id?: string;
        parent_platform_id?: string;
        conversation_platform_id: string | null;
      };
      events: components['schemas']['WorkflowEvent'][];
    };
    ValidateWorkflowResponse: {
      valid: boolean;
      errors?: string[];
    };
    ValidateWorkflowBody: {
      definition: {
        [key: string]: unknown;
      };
    };
    GetWorkflowResponse: {
      workflow: components['schemas']['WorkflowDefinition'];
      filename: string;
      source: components['schemas']['WorkflowSource'];
    };
    SaveWorkflowBody: {
      definition: {
        [key: string]: unknown;
      };
    };
    DeleteWorkflowResponse: {
      deleted: boolean;
      name: string;
    };
    CommandEntry: {
      name: string;
      source: components['schemas']['WorkflowSource'];
    };
    CommandListResponse: {
      commands: components['schemas']['CommandEntry'][];
    };
    ArtifactFile: {
      path: string;
      size: number;
      modifiedAt: string;
    };
    ListArtifactsResponse: {
      files: components['schemas']['ArtifactFile'][];
    };
    ProviderDefaults: {
      [key: string]: unknown;
    };
    SafeConfig: {
      botName: string;
      assistant: string;
      assistants: {
        [key: string]: components['schemas']['ProviderDefaults'];
      };
      streaming: {
        /** @enum {string} */
        telegram: 'stream' | 'batch';
        /** @enum {string} */
        discord: 'stream' | 'batch';
        /** @enum {string} */
        slack: 'stream' | 'batch';
      };
      concurrency: {
        maxConversations: number;
      };
      defaults: {
        copyDefaults: boolean;
        loadDefaultCommands: boolean;
        loadDefaultWorkflows: boolean;
      };
    };
    ConfigResponse: {
      config: components['schemas']['SafeConfig'];
      database: string;
    };
    UpdateAssistantConfigBody: {
      assistant?: string;
      assistants?: {
        [key: string]: components['schemas']['ProviderDefaults'];
      };
    };
    ProviderCapabilities: {
      sessionResume: boolean;
      mcp: boolean;
      hooks: boolean;
      skills: boolean;
      toolRestrictions: boolean;
      structuredOutput: boolean;
      envInjection: boolean;
      costControl: boolean;
      effortControl: boolean;
      thinkingControl: boolean;
      fallbackModel: boolean;
      sandbox: boolean;
    };
    ProviderInfo: {
      id: string;
      displayName: string;
      capabilities: components['schemas']['ProviderCapabilities'];
      builtIn: boolean;
    };
    ProviderListResponse: {
      providers: components['schemas']['ProviderInfo'][];
    };
    IsolationEnvironment: {
      id: string;
      codebase_id: string;
      branch_name: string;
      working_path: string;
      status: string;
      created_at: string;
      updated_at: string;
      days_since_activity: number;
    };
    CodebaseEnvironmentsResponse: {
      environments: components['schemas']['IsolationEnvironment'][];
    };
    HealthResponse: {
      status: string;
      adapter: string;
      concurrency: {
        [key: string]: unknown;
      };
      runningWorkflows: number;
      version?: string;
      is_docker: boolean;
      activePlatforms?: string[];
    };
    UpdateCheckResponse: {
      updateAvailable: boolean;
      currentVersion: string;
      latestVersion: string;
      releaseUrl: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
